In [1]:
import pandas_datareader.data as web
import datetime
import pandas as pd
import numpy as np

In [2]:
# 보라 / 11월 1일 월요일 / 19:50 마감 
close = [342, 343, 342, 342, 340, 342, 341, 339, 340, 338, 337, 339, 340, 339, 340, 341, 341, 338, 336, 336
         ,337, 337, 337, 339, 340, 340, 341, 341, 344, 344, 344, 350, 349, 343, 345, 346, 346, 346, 346, 347]
close = pd.DataFrame(close,columns = ['Close'])

In [3]:
def TSI(data, n_days1 = 10, n_days2 = 5, signal = 5):
    delta = data['Close'].diff()

    mom1 = delta.ewm(span=n_days1).mean().ewm(span=n_days2).mean()
    mom2 = delta.abs().ewm(span=n_days1).mean().ewm(span=n_days2).mean()
    # tsi
    data['tsi'] = mom1/mom2
    #EMA
    data['signal'] = data['tsi'].ewm(span=signal).mean()

    return data[['tsi','signal']]

In [4]:
TSI(close)

         tsi    signal
0        NaN       NaN
1   1.000000  1.000000
2   0.340000  0.604000
3   0.186048  0.406023
4  -0.221444  0.145382
5  -0.089014  0.055401
6  -0.118896 -0.008289
7  -0.252359 -0.094704
8  -0.232890 -0.142636
9  -0.309051 -0.199589
10 -0.382303 -0.261569
11 -0.283132 -0.268841
12 -0.171245 -0.236056
13 -0.150121 -0.207263
14 -0.082622 -0.165573
15  0.009335 -0.107137
16  0.065056 -0.049652
17 -0.064352 -0.054557
18 -0.215339 -0.108187
19 -0.294834 -0.170431
20 -0.276583 -0.205826
21 -0.265477 -0.225713
22 -0.258128 -0.236520
23 -0.102071 -0.191699
24  0.050547 -0.110946
25  0.139780 -0.027367
26  0.250808  0.065361
27  0.318852  0.149859
28  0.488389  0.262704
29  0.572366  0.365925
30  0.621683  0.451178
31  0.763778  0.555378
32  0.732781  0.614513
33  0.339316  0.522780
34  0.234454  0.426671
35  0.209662  0.354335
36  0.196037  0.301569
37  0.187566  0.263568
38  0.181890  0.236342
39  0.214056  0.228913